version: '3.8'

services:
  web-terminal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu_bypass_terminal
    ports:
      - "8080:8080"
    privileged: true
    restart: unless-stopped
